trailing_whitespace:
  ignores_empty_lines: true
  
vertical_whitespace:
  max_empty_lines: 2
  
line_length:
  warning: 200
  error: 1000
  
type_name:
  allowed_symbols: "_"

identifier_name:
  min_length: 2
  allowed_symbols: "_"
  
nesting:
  type_level: 4

disabled_rules:
  - weak_delegate
